#version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/app/staticfiles
      #- staticfiles:/staticfiles
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static:/app/staticfiles
      #- staticfiles:/staticfiles

    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    restart: always

volumes:
  static:
  #staticfiles:
  