# Generated by Django 5.1 on 2024-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название аттракциона')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Рост')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп инфа')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Работает')),
                ('order', models.IntegerField(default=50, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Аттракцион',
                'verbose_name_plural': 'Аттракционы',
            },
        ),
    ]
