# Generated by Django 5.1 on 2024-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
    ]
