# Generated by Django 5.1 on 2024-09-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_attraction_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyAttraction',
            fields=[
            ],
            options={
                'verbose_name': 'Аттракцион',
                'verbose_name_plural': 'Аттракционы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainapp.attraction',),
        ),
    ]
